import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Header from "@/components/Home/Header";
// import Footer from "@/components/Home/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-900 text-white">
      <body className={inter.className}>
        <Provider>
          <Header />
          {children}
          {/* <Footer /> */}
        </Provider>
      </body>
    </html>
  );
}